services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: DBP02
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "prueba01@tc.com"
      PGADMIN_DEFAULT_PASSWORD: "password1234"
  
  neo4j:
    image: neo4j:5.20
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/your_password
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - ./init-map/neo4j/logs:/logs
      - ./init-map/neo4j/config:/config
      - ./init-map/neo4j/data:/data
      - ./init-map/neo4j/plugins:/plugins
      - ./init-map/neo4j/import:/import

    restart: always

    
